/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as GateRouteImport } from './routes/gate'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PRouteImport } from './routes/p'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ProductRouteImport } from './routes/product'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as SspRouteRouteImport } from './routes/ssp/route'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as AdminFestivalIdRouteRouteImport } from './routes/admin/$festivalId/route'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as FestivalsIndexRouteImport } from './routes/festivals/index'
import { Route as FestivalsSlugRouteImport } from './routes/festivals/$slug'
import { Route as SspIndexRouteImport } from './routes/ssp/index'
import { Route as SspAnalyticsRouteImport } from './routes/ssp/analytics'
import { Route as SspApplicationsRouteImport } from './routes/ssp/applications'
import { Route as SspEventsRouteImport } from './routes/ssp/events'
import { Route as SspFestivalsRouteRouteImport } from './routes/ssp/festivals/route'
import { Route as SspLoginRouteImport } from './routes/ssp/login'
import { Route as SspNetworkRouteImport } from './routes/ssp/network'
import { Route as SspOrganizationsRouteImport } from './routes/ssp/organizations'
import { Route as SspUsersRouteImport } from './routes/ssp/users'
import { Route as AdminFestivalIdIndexRouteImport } from './routes/admin/$festivalId/index'
import { Route as AdminFestivalIdAiRouteImport } from './routes/admin/$festivalId/ai'
import { Route as AdminFestivalIdAnalyticsRouteImport } from './routes/admin/$festivalId/analytics'
import { Route as AdminFestivalIdCmsRouteImport } from './routes/admin/$festivalId/cms'
import { Route as AdminFestivalIdEventsRouteImport } from './routes/admin/$festivalId/events'
import { Route as AdminFestivalIdGatesRouteImport } from './routes/admin/$festivalId/gates'
import { Route as AdminFestivalIdIncomeRouteImport } from './routes/admin/$festivalId/income'
import { Route as AdminFestivalIdParticipantsRouteImport } from './routes/admin/$festivalId/participants'
import { Route as AdminFestivalIdPlanningRouteImport } from './routes/admin/$festivalId/planning'
import { Route as AdminFestivalIdPublishRouteImport } from './routes/admin/$festivalId/publish'
import { Route as AdminFestivalIdStaffRouteImport } from './routes/admin/$festivalId/staff'
import { Route as AdminFestivalIdVenuesRouteImport } from './routes/admin/$festivalId/venues'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SspFestivalsIndexRouteImport } from './routes/ssp/festivals/index'
import { Route as SspFestivalsFestivalIdRouteImport } from './routes/ssp/festivals/$festivalId'
import { Route as AdminFestivalIdEventsEventIdRouteImport } from './routes/admin/$festivalId/events.$eventId'
import { Route as AdminFestivalIdEventsNewRouteImport } from './routes/admin/$festivalId/events.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const SspRouteRoute = SspRouteRouteImport.update({
  id: '/ssp',
  path: '/ssp',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFestivalIdRouteRoute = AdminFestivalIdRouteRouteImport.update({
  id: '/admin/$festivalId',
  path: '/admin/$festivalId',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsIndexRoute = FestivalsIndexRouteImport.update({
  id: '/festivals/',
  path: '/festivals/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsSlugRoute = FestivalsSlugRouteImport.update({
  id: '/festivals/$slug',
  path: '/festivals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SspIndexRoute = SspIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspAnalyticsRoute = SspAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspApplicationsRoute = SspApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspEventsRoute = SspEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspFestivalsRouteRoute = SspFestivalsRouteRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspLoginRoute = SspLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspNetworkRoute = SspNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspOrganizationsRoute = SspOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SspRouteRoute,
} as any)
const SspUsersRoute = SspUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SspRouteRoute,
} as any)
const AdminFestivalIdIndexRoute = AdminFestivalIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdAiRoute = AdminFestivalIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdAnalyticsRoute =
  AdminFestivalIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminFestivalIdRouteRoute,
  } as any)
const AdminFestivalIdCmsRoute = AdminFestivalIdCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdEventsRoute = AdminFestivalIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdGatesRoute = AdminFestivalIdGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdIncomeRoute = AdminFestivalIdIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdParticipantsRoute =
  AdminFestivalIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AdminFestivalIdRouteRoute,
  } as any)
const AdminFestivalIdPlanningRoute = AdminFestivalIdPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdPublishRoute = AdminFestivalIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdStaffRoute = AdminFestivalIdStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const AdminFestivalIdVenuesRoute = AdminFestivalIdVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminFestivalIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SspFestivalsIndexRoute = SspFestivalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SspFestivalsRouteRoute,
} as any)
const SspFestivalsFestivalIdRoute = SspFestivalsFestivalIdRouteImport.update({
  id: '/$festivalId',
  path: '/$festivalId',
  getParentRoute: () => SspFestivalsRouteRoute,
} as any)
const AdminFestivalIdEventsEventIdRoute =
  AdminFestivalIdEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AdminFestivalIdEventsRoute,
  } as any)
const AdminFestivalIdEventsNewRoute =
  AdminFestivalIdEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminFestivalIdEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ssp': typeof SspRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/gate': typeof GateRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/p': typeof PRoute
  '/packages': typeof PackagesRoute
  '/pay': typeof PayRoute
  '/product': typeof ProductRoute
  '/samples': typeof SamplesRoute
  '/sponsor': typeof SponsorRoute
  '/vendor': typeof VendorRoute
  '/admin/$festivalId': typeof AdminFestivalIdRouteRouteWithChildren
  '/ssp/festivals': typeof SspFestivalsRouteRouteWithChildren
  '/f/$slug': typeof FSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/ssp/analytics': typeof SspAnalyticsRoute
  '/ssp/applications': typeof SspApplicationsRoute
  '/ssp/events': typeof SspEventsRoute
  '/ssp/login': typeof SspLoginRoute
  '/ssp/network': typeof SspNetworkRoute
  '/ssp/organizations': typeof SspOrganizationsRoute
  '/ssp/users': typeof SspUsersRoute
  '/festivals/': typeof FestivalsIndexRoute
  '/ssp/': typeof SspIndexRoute
  '/admin/$festivalId/ai': typeof AdminFestivalIdAiRoute
  '/admin/$festivalId/analytics': typeof AdminFestivalIdAnalyticsRoute
  '/admin/$festivalId/cms': typeof AdminFestivalIdCmsRoute
  '/admin/$festivalId/events': typeof AdminFestivalIdEventsRouteWithChildren
  '/admin/$festivalId/gates': typeof AdminFestivalIdGatesRoute
  '/admin/$festivalId/income': typeof AdminFestivalIdIncomeRoute
  '/admin/$festivalId/participants': typeof AdminFestivalIdParticipantsRoute
  '/admin/$festivalId/planning': typeof AdminFestivalIdPlanningRoute
  '/admin/$festivalId/publish': typeof AdminFestivalIdPublishRoute
  '/admin/$festivalId/staff': typeof AdminFestivalIdStaffRoute
  '/admin/$festivalId/venues': typeof AdminFestivalIdVenuesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ssp/festivals/$festivalId': typeof SspFestivalsFestivalIdRoute
  '/admin/$festivalId/': typeof AdminFestivalIdIndexRoute
  '/ssp/festivals/': typeof SspFestivalsIndexRoute
  '/admin/$festivalId/events/$eventId': typeof AdminFestivalIdEventsEventIdRoute
  '/admin/$festivalId/events/new': typeof AdminFestivalIdEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/gate': typeof GateRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/p': typeof PRoute
  '/packages': typeof PackagesRoute
  '/pay': typeof PayRoute
  '/product': typeof ProductRoute
  '/samples': typeof SamplesRoute
  '/sponsor': typeof SponsorRoute
  '/vendor': typeof VendorRoute
  '/f/$slug': typeof FSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/ssp/analytics': typeof SspAnalyticsRoute
  '/ssp/applications': typeof SspApplicationsRoute
  '/ssp/events': typeof SspEventsRoute
  '/ssp/login': typeof SspLoginRoute
  '/ssp/network': typeof SspNetworkRoute
  '/ssp/organizations': typeof SspOrganizationsRoute
  '/ssp/users': typeof SspUsersRoute
  '/festivals': typeof FestivalsIndexRoute
  '/ssp': typeof SspIndexRoute
  '/admin/$festivalId/ai': typeof AdminFestivalIdAiRoute
  '/admin/$festivalId/analytics': typeof AdminFestivalIdAnalyticsRoute
  '/admin/$festivalId/cms': typeof AdminFestivalIdCmsRoute
  '/admin/$festivalId/events': typeof AdminFestivalIdEventsRouteWithChildren
  '/admin/$festivalId/gates': typeof AdminFestivalIdGatesRoute
  '/admin/$festivalId/income': typeof AdminFestivalIdIncomeRoute
  '/admin/$festivalId/participants': typeof AdminFestivalIdParticipantsRoute
  '/admin/$festivalId/planning': typeof AdminFestivalIdPlanningRoute
  '/admin/$festivalId/publish': typeof AdminFestivalIdPublishRoute
  '/admin/$festivalId/staff': typeof AdminFestivalIdStaffRoute
  '/admin/$festivalId/venues': typeof AdminFestivalIdVenuesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ssp/festivals/$festivalId': typeof SspFestivalsFestivalIdRoute
  '/admin/$festivalId': typeof AdminFestivalIdIndexRoute
  '/ssp/festivals': typeof SspFestivalsIndexRoute
  '/admin/$festivalId/events/$eventId': typeof AdminFestivalIdEventsEventIdRoute
  '/admin/$festivalId/events/new': typeof AdminFestivalIdEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ssp': typeof SspRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/gate': typeof GateRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/p': typeof PRoute
  '/packages': typeof PackagesRoute
  '/pay': typeof PayRoute
  '/product': typeof ProductRoute
  '/samples': typeof SamplesRoute
  '/sponsor': typeof SponsorRoute
  '/vendor': typeof VendorRoute
  '/admin/$festivalId': typeof AdminFestivalIdRouteRouteWithChildren
  '/ssp/festivals': typeof SspFestivalsRouteRouteWithChildren
  '/f/$slug': typeof FSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/ssp/analytics': typeof SspAnalyticsRoute
  '/ssp/applications': typeof SspApplicationsRoute
  '/ssp/events': typeof SspEventsRoute
  '/ssp/login': typeof SspLoginRoute
  '/ssp/network': typeof SspNetworkRoute
  '/ssp/organizations': typeof SspOrganizationsRoute
  '/ssp/users': typeof SspUsersRoute
  '/festivals/': typeof FestivalsIndexRoute
  '/ssp/': typeof SspIndexRoute
  '/admin/$festivalId/ai': typeof AdminFestivalIdAiRoute
  '/admin/$festivalId/analytics': typeof AdminFestivalIdAnalyticsRoute
  '/admin/$festivalId/cms': typeof AdminFestivalIdCmsRoute
  '/admin/$festivalId/events': typeof AdminFestivalIdEventsRouteWithChildren
  '/admin/$festivalId/gates': typeof AdminFestivalIdGatesRoute
  '/admin/$festivalId/income': typeof AdminFestivalIdIncomeRoute
  '/admin/$festivalId/participants': typeof AdminFestivalIdParticipantsRoute
  '/admin/$festivalId/planning': typeof AdminFestivalIdPlanningRoute
  '/admin/$festivalId/publish': typeof AdminFestivalIdPublishRoute
  '/admin/$festivalId/staff': typeof AdminFestivalIdStaffRoute
  '/admin/$festivalId/venues': typeof AdminFestivalIdVenuesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ssp/festivals/$festivalId': typeof SspFestivalsFestivalIdRoute
  '/admin/$festivalId/': typeof AdminFestivalIdIndexRoute
  '/ssp/festivals/': typeof SspFestivalsIndexRoute
  '/admin/$festivalId/events/$eventId': typeof AdminFestivalIdEventsEventIdRoute
  '/admin/$festivalId/events/new': typeof AdminFestivalIdEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ssp'
    | '/apply'
    | '/gate'
    | '/hub'
    | '/login'
    | '/p'
    | '/packages'
    | '/pay'
    | '/product'
    | '/samples'
    | '/sponsor'
    | '/vendor'
    | '/admin/$festivalId'
    | '/ssp/festivals'
    | '/f/$slug'
    | '/festivals/$slug'
    | '/ssp/analytics'
    | '/ssp/applications'
    | '/ssp/events'
    | '/ssp/login'
    | '/ssp/network'
    | '/ssp/organizations'
    | '/ssp/users'
    | '/festivals/'
    | '/ssp/'
    | '/admin/$festivalId/ai'
    | '/admin/$festivalId/analytics'
    | '/admin/$festivalId/cms'
    | '/admin/$festivalId/events'
    | '/admin/$festivalId/gates'
    | '/admin/$festivalId/income'
    | '/admin/$festivalId/participants'
    | '/admin/$festivalId/planning'
    | '/admin/$festivalId/publish'
    | '/admin/$festivalId/staff'
    | '/admin/$festivalId/venues'
    | '/api/auth/$'
    | '/ssp/festivals/$festivalId'
    | '/admin/$festivalId/'
    | '/ssp/festivals/'
    | '/admin/$festivalId/events/$eventId'
    | '/admin/$festivalId/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/gate'
    | '/hub'
    | '/login'
    | '/p'
    | '/packages'
    | '/pay'
    | '/product'
    | '/samples'
    | '/sponsor'
    | '/vendor'
    | '/f/$slug'
    | '/festivals/$slug'
    | '/ssp/analytics'
    | '/ssp/applications'
    | '/ssp/events'
    | '/ssp/login'
    | '/ssp/network'
    | '/ssp/organizations'
    | '/ssp/users'
    | '/festivals'
    | '/ssp'
    | '/admin/$festivalId/ai'
    | '/admin/$festivalId/analytics'
    | '/admin/$festivalId/cms'
    | '/admin/$festivalId/events'
    | '/admin/$festivalId/gates'
    | '/admin/$festivalId/income'
    | '/admin/$festivalId/participants'
    | '/admin/$festivalId/planning'
    | '/admin/$festivalId/publish'
    | '/admin/$festivalId/staff'
    | '/admin/$festivalId/venues'
    | '/api/auth/$'
    | '/ssp/festivals/$festivalId'
    | '/admin/$festivalId'
    | '/ssp/festivals'
    | '/admin/$festivalId/events/$eventId'
    | '/admin/$festivalId/events/new'
  id:
    | '__root__'
    | '/'
    | '/ssp'
    | '/apply'
    | '/gate'
    | '/hub'
    | '/login'
    | '/p'
    | '/packages'
    | '/pay'
    | '/product'
    | '/samples'
    | '/sponsor'
    | '/vendor'
    | '/admin/$festivalId'
    | '/ssp/festivals'
    | '/f/$slug'
    | '/festivals/$slug'
    | '/ssp/analytics'
    | '/ssp/applications'
    | '/ssp/events'
    | '/ssp/login'
    | '/ssp/network'
    | '/ssp/organizations'
    | '/ssp/users'
    | '/festivals/'
    | '/ssp/'
    | '/admin/$festivalId/ai'
    | '/admin/$festivalId/analytics'
    | '/admin/$festivalId/cms'
    | '/admin/$festivalId/events'
    | '/admin/$festivalId/gates'
    | '/admin/$festivalId/income'
    | '/admin/$festivalId/participants'
    | '/admin/$festivalId/planning'
    | '/admin/$festivalId/publish'
    | '/admin/$festivalId/staff'
    | '/admin/$festivalId/venues'
    | '/api/auth/$'
    | '/ssp/festivals/$festivalId'
    | '/admin/$festivalId/'
    | '/ssp/festivals/'
    | '/admin/$festivalId/events/$eventId'
    | '/admin/$festivalId/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SspRouteRoute: typeof SspRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  GateRoute: typeof GateRoute
  HubRoute: typeof HubRoute
  LoginRoute: typeof LoginRoute
  PRoute: typeof PRoute
  PackagesRoute: typeof PackagesRoute
  PayRoute: typeof PayRoute
  ProductRoute: typeof ProductRoute
  SamplesRoute: typeof SamplesRoute
  SponsorRoute: typeof SponsorRoute
  VendorRoute: typeof VendorRoute
  AdminFestivalIdRouteRoute: typeof AdminFestivalIdRouteRouteWithChildren
  FSlugRoute: typeof FSlugRoute
  FestivalsSlugRoute: typeof FestivalsSlugRoute
  FestivalsIndexRoute: typeof FestivalsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssp': {
      id: '/ssp'
      path: '/ssp'
      fullPath: '/ssp'
      preLoaderRoute: typeof SspRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$festivalId': {
      id: '/admin/$festivalId'
      path: '/admin/$festivalId'
      fullPath: '/admin/$festivalId'
      preLoaderRoute: typeof AdminFestivalIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/': {
      id: '/festivals/'
      path: '/festivals'
      fullPath: '/festivals/'
      preLoaderRoute: typeof FestivalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/$slug': {
      id: '/festivals/$slug'
      path: '/festivals/$slug'
      fullPath: '/festivals/$slug'
      preLoaderRoute: typeof FestivalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssp/': {
      id: '/ssp/'
      path: '/'
      fullPath: '/ssp/'
      preLoaderRoute: typeof SspIndexRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/analytics': {
      id: '/ssp/analytics'
      path: '/analytics'
      fullPath: '/ssp/analytics'
      preLoaderRoute: typeof SspAnalyticsRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/applications': {
      id: '/ssp/applications'
      path: '/applications'
      fullPath: '/ssp/applications'
      preLoaderRoute: typeof SspApplicationsRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/events': {
      id: '/ssp/events'
      path: '/events'
      fullPath: '/ssp/events'
      preLoaderRoute: typeof SspEventsRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/festivals': {
      id: '/ssp/festivals'
      path: '/festivals'
      fullPath: '/ssp/festivals'
      preLoaderRoute: typeof SspFestivalsRouteRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/login': {
      id: '/ssp/login'
      path: '/login'
      fullPath: '/ssp/login'
      preLoaderRoute: typeof SspLoginRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/network': {
      id: '/ssp/network'
      path: '/network'
      fullPath: '/ssp/network'
      preLoaderRoute: typeof SspNetworkRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/organizations': {
      id: '/ssp/organizations'
      path: '/organizations'
      fullPath: '/ssp/organizations'
      preLoaderRoute: typeof SspOrganizationsRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/ssp/users': {
      id: '/ssp/users'
      path: '/users'
      fullPath: '/ssp/users'
      preLoaderRoute: typeof SspUsersRouteImport
      parentRoute: typeof SspRouteRoute
    }
    '/admin/$festivalId/': {
      id: '/admin/$festivalId/'
      path: '/'
      fullPath: '/admin/$festivalId/'
      preLoaderRoute: typeof AdminFestivalIdIndexRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/ai': {
      id: '/admin/$festivalId/ai'
      path: '/ai'
      fullPath: '/admin/$festivalId/ai'
      preLoaderRoute: typeof AdminFestivalIdAiRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/analytics': {
      id: '/admin/$festivalId/analytics'
      path: '/analytics'
      fullPath: '/admin/$festivalId/analytics'
      preLoaderRoute: typeof AdminFestivalIdAnalyticsRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/cms': {
      id: '/admin/$festivalId/cms'
      path: '/cms'
      fullPath: '/admin/$festivalId/cms'
      preLoaderRoute: typeof AdminFestivalIdCmsRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/events': {
      id: '/admin/$festivalId/events'
      path: '/events'
      fullPath: '/admin/$festivalId/events'
      preLoaderRoute: typeof AdminFestivalIdEventsRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/gates': {
      id: '/admin/$festivalId/gates'
      path: '/gates'
      fullPath: '/admin/$festivalId/gates'
      preLoaderRoute: typeof AdminFestivalIdGatesRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/income': {
      id: '/admin/$festivalId/income'
      path: '/income'
      fullPath: '/admin/$festivalId/income'
      preLoaderRoute: typeof AdminFestivalIdIncomeRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/participants': {
      id: '/admin/$festivalId/participants'
      path: '/participants'
      fullPath: '/admin/$festivalId/participants'
      preLoaderRoute: typeof AdminFestivalIdParticipantsRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/planning': {
      id: '/admin/$festivalId/planning'
      path: '/planning'
      fullPath: '/admin/$festivalId/planning'
      preLoaderRoute: typeof AdminFestivalIdPlanningRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/publish': {
      id: '/admin/$festivalId/publish'
      path: '/publish'
      fullPath: '/admin/$festivalId/publish'
      preLoaderRoute: typeof AdminFestivalIdPublishRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/staff': {
      id: '/admin/$festivalId/staff'
      path: '/staff'
      fullPath: '/admin/$festivalId/staff'
      preLoaderRoute: typeof AdminFestivalIdStaffRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/admin/$festivalId/venues': {
      id: '/admin/$festivalId/venues'
      path: '/venues'
      fullPath: '/admin/$festivalId/venues'
      preLoaderRoute: typeof AdminFestivalIdVenuesRouteImport
      parentRoute: typeof AdminFestivalIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssp/festivals/': {
      id: '/ssp/festivals/'
      path: '/'
      fullPath: '/ssp/festivals/'
      preLoaderRoute: typeof SspFestivalsIndexRouteImport
      parentRoute: typeof SspFestivalsRouteRoute
    }
    '/ssp/festivals/$festivalId': {
      id: '/ssp/festivals/$festivalId'
      path: '/$festivalId'
      fullPath: '/ssp/festivals/$festivalId'
      preLoaderRoute: typeof SspFestivalsFestivalIdRouteImport
      parentRoute: typeof SspFestivalsRouteRoute
    }
    '/admin/$festivalId/events/$eventId': {
      id: '/admin/$festivalId/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/$festivalId/events/$eventId'
      preLoaderRoute: typeof AdminFestivalIdEventsEventIdRouteImport
      parentRoute: typeof AdminFestivalIdEventsRoute
    }
    '/admin/$festivalId/events/new': {
      id: '/admin/$festivalId/events/new'
      path: '/new'
      fullPath: '/admin/$festivalId/events/new'
      preLoaderRoute: typeof AdminFestivalIdEventsNewRouteImport
      parentRoute: typeof AdminFestivalIdEventsRoute
    }
  }
}

interface SspFestivalsRouteRouteChildren {
  SspFestivalsFestivalIdRoute: typeof SspFestivalsFestivalIdRoute
  SspFestivalsIndexRoute: typeof SspFestivalsIndexRoute
}

const SspFestivalsRouteRouteChildren: SspFestivalsRouteRouteChildren = {
  SspFestivalsFestivalIdRoute: SspFestivalsFestivalIdRoute,
  SspFestivalsIndexRoute: SspFestivalsIndexRoute,
}

const SspFestivalsRouteRouteWithChildren =
  SspFestivalsRouteRoute._addFileChildren(SspFestivalsRouteRouteChildren)

interface SspRouteRouteChildren {
  SspFestivalsRouteRoute: typeof SspFestivalsRouteRouteWithChildren
  SspAnalyticsRoute: typeof SspAnalyticsRoute
  SspApplicationsRoute: typeof SspApplicationsRoute
  SspEventsRoute: typeof SspEventsRoute
  SspLoginRoute: typeof SspLoginRoute
  SspNetworkRoute: typeof SspNetworkRoute
  SspOrganizationsRoute: typeof SspOrganizationsRoute
  SspUsersRoute: typeof SspUsersRoute
  SspIndexRoute: typeof SspIndexRoute
}

const SspRouteRouteChildren: SspRouteRouteChildren = {
  SspFestivalsRouteRoute: SspFestivalsRouteRouteWithChildren,
  SspAnalyticsRoute: SspAnalyticsRoute,
  SspApplicationsRoute: SspApplicationsRoute,
  SspEventsRoute: SspEventsRoute,
  SspLoginRoute: SspLoginRoute,
  SspNetworkRoute: SspNetworkRoute,
  SspOrganizationsRoute: SspOrganizationsRoute,
  SspUsersRoute: SspUsersRoute,
  SspIndexRoute: SspIndexRoute,
}

const SspRouteRouteWithChildren = SspRouteRoute._addFileChildren(
  SspRouteRouteChildren,
)

interface AdminFestivalIdEventsRouteChildren {
  AdminFestivalIdEventsEventIdRoute: typeof AdminFestivalIdEventsEventIdRoute
  AdminFestivalIdEventsNewRoute: typeof AdminFestivalIdEventsNewRoute
}

const AdminFestivalIdEventsRouteChildren: AdminFestivalIdEventsRouteChildren = {
  AdminFestivalIdEventsEventIdRoute: AdminFestivalIdEventsEventIdRoute,
  AdminFestivalIdEventsNewRoute: AdminFestivalIdEventsNewRoute,
}

const AdminFestivalIdEventsRouteWithChildren =
  AdminFestivalIdEventsRoute._addFileChildren(
    AdminFestivalIdEventsRouteChildren,
  )

interface AdminFestivalIdRouteRouteChildren {
  AdminFestivalIdAiRoute: typeof AdminFestivalIdAiRoute
  AdminFestivalIdAnalyticsRoute: typeof AdminFestivalIdAnalyticsRoute
  AdminFestivalIdCmsRoute: typeof AdminFestivalIdCmsRoute
  AdminFestivalIdEventsRoute: typeof AdminFestivalIdEventsRouteWithChildren
  AdminFestivalIdGatesRoute: typeof AdminFestivalIdGatesRoute
  AdminFestivalIdIncomeRoute: typeof AdminFestivalIdIncomeRoute
  AdminFestivalIdParticipantsRoute: typeof AdminFestivalIdParticipantsRoute
  AdminFestivalIdPlanningRoute: typeof AdminFestivalIdPlanningRoute
  AdminFestivalIdPublishRoute: typeof AdminFestivalIdPublishRoute
  AdminFestivalIdStaffRoute: typeof AdminFestivalIdStaffRoute
  AdminFestivalIdVenuesRoute: typeof AdminFestivalIdVenuesRoute
  AdminFestivalIdIndexRoute: typeof AdminFestivalIdIndexRoute
}

const AdminFestivalIdRouteRouteChildren: AdminFestivalIdRouteRouteChildren = {
  AdminFestivalIdAiRoute: AdminFestivalIdAiRoute,
  AdminFestivalIdAnalyticsRoute: AdminFestivalIdAnalyticsRoute,
  AdminFestivalIdCmsRoute: AdminFestivalIdCmsRoute,
  AdminFestivalIdEventsRoute: AdminFestivalIdEventsRouteWithChildren,
  AdminFestivalIdGatesRoute: AdminFestivalIdGatesRoute,
  AdminFestivalIdIncomeRoute: AdminFestivalIdIncomeRoute,
  AdminFestivalIdParticipantsRoute: AdminFestivalIdParticipantsRoute,
  AdminFestivalIdPlanningRoute: AdminFestivalIdPlanningRoute,
  AdminFestivalIdPublishRoute: AdminFestivalIdPublishRoute,
  AdminFestivalIdStaffRoute: AdminFestivalIdStaffRoute,
  AdminFestivalIdVenuesRoute: AdminFestivalIdVenuesRoute,
  AdminFestivalIdIndexRoute: AdminFestivalIdIndexRoute,
}

const AdminFestivalIdRouteRouteWithChildren =
  AdminFestivalIdRouteRoute._addFileChildren(AdminFestivalIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SspRouteRoute: SspRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  GateRoute: GateRoute,
  HubRoute: HubRoute,
  LoginRoute: LoginRoute,
  PRoute: PRoute,
  PackagesRoute: PackagesRoute,
  PayRoute: PayRoute,
  ProductRoute: ProductRoute,
  SamplesRoute: SamplesRoute,
  SponsorRoute: SponsorRoute,
  VendorRoute: VendorRoute,
  AdminFestivalIdRouteRoute: AdminFestivalIdRouteRouteWithChildren,
  FSlugRoute: FSlugRoute,
  FestivalsSlugRoute: FestivalsSlugRoute,
  FestivalsIndexRoute: FestivalsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
